#!/bin/sh
##########################################################################
# If not stated otherwise in this file or this component's Licenses.txt
# file the following copyright and licenses apply:
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################
MOCA_IP=127.0.0.1
VALUE=`/usr/local/tr69/host-if -H $MOCA_IP -p 56981 -g $1 | grep Value | tr -d '"' | sed -e 's/Value.* ://g'`
if [ "$1" == "Device.MoCA.Interface.1.Enable" ];
then
   if [ $VALUE -eq 1 ];
   then
       echo "True"
   else
       echo "False"
   fi
elif [ "$1" == "Device.MoCA.Interface.1.PrivacyEnabledSetting" ];
then
   if [ $VALUE -eq 1 ];
   then
       echo "Enabled"
   else
       echo "Disabled"
   fi
elif [ "$1" = "Device.MoCA.Interface.1.PreferredNC" ];
then
   if [ $VALUE -eq 1 ];
   then
       echo "True"
   else
       echo "False"
   fi
elif [ "$1" == "Device.Services.STBService.1.Components.VideoOutput.1.HDCP" ];
then
   if [ $VALUE -eq 1 ];
   then
       echo "True"
   else
       echo "False"
   fi
elif [ "$1" == "Device.Time.CurrentLocalTime" ];
then
  echo `date +"%r"`
else
   echo $VALUE
fi
echo "name: ${1} value: ${VALUE}" >> /tmp/test.log
